equire 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'
require 'parallel'
require 'json'
require 'yard'


YARD::Rake::YardocTask.new(:yard) do |t|
t.files   = ['features/**/*.feature', 'features/**/*.rb']
#t.options = ['--any', '--extra', '--opts'] # optional
end

Cucumber::Rake::Task.new(:cucumber) do |t|
  t.cucumber_opts = "features --format pretty"
end

task :parallel_cucumber do
  sh "bundle exec parallel_cucumber features/"
end

task :rubocop do
  sh "bundle exec rubocop features/"
end
