require 'rubygems'
require 'bundler/setup'
require "Capybara/cucumber"
require "rspec"
require 'capybara/poltergeist'
require 'selenium-webdriver'
require 'rubocop'
require 'bddfire'
require 'rbconfig'
include RbConfig