require 'rubygems'
require 'bundler/setup'
require "capybara"
require 'bddfire'
require "cucumber"
require "rspec"
require 'selenium-webdriver'
require 'rbconfig'
require 'require_all'
include RbConfig